name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  ci:
    # run on 1) push, 2) external PRs, 3) github-actions[bot] PRs
    # do not run on internal, non-steward PRs since those will be run by push to branch
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.full_name != github.repository ||
      github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        cache: 'sbt'
        java-version: 21
    - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1, specifically v1.1.14
    - name: Compile
      run: sbt -v compile
    - name: Test
      run: sbt -v test

  publish:
    name: Publish release
    needs: [ci]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-24.04
    env:
      JAVA_OPTS: -Xmx4G
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'sbt'
          java-version: 21
      - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1, specifically v1.1.14
      - name: Compile
        run: sbt compile
      - name: Publish artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Extract version from commit message
        run: |
          version=${GITHUB_REF/refs\/tags\/v/}
          echo "VERSION=$version" >> $GITHUB_ENV
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
      - name: Publish release notes
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6, specifically v6.1.0
        with:
          config-name: release-drafter.yml
          publish: true
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          version: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
